services:
  backend:
    image: viljaah/webproject-backend:latest
    ports:
      - "8286:8286"
    restart: always 
    env_file:
      - .env

  frontend:
    image: viljaah/webproject-front-end:latest
    ports:
      - "8186:8186"
    env_file:
      - .env
    command: sh -c "npm install @rollup/rollup-linux-x64-gnu && npm run build && npx serve -s dist -l 8186"   
    restart: always
    depends_on:
      - backend
