### token eventually
@token = 987654321
### study id
@studyId = 123456789
### questions id
@questionId = 0192837465

### create a study
POST http://localhost:8080/api/studies
Content-Type: application/json
Authorization: {{token}}

{
  "studyTitle": "First study test",
  "description": "A study about poems",
  "published": false,
  "questions": []
}

### get all studies
GET http://localhost:8080/api/studies

### get study by id
GET http://localhost:8080/api/studies/{{studyId}}

### update study
PATCH http://localhost:8080/api/studies/{{studyId}}
Content-Type: application/json
Authorization: {{token}}

{
  "studyTitle": "Updated study test",
  "description": "A study about books"
}

### delete study
DELETE http://localhost:8080/api/studies/{{studyId}}
Authorization: {{token}}

### publish study
PATCH http://localhost:8080/api/studies/{{studyId}}/public
Authorization: {{token}}

### get study sharable url
GET http://localhost:8080/api/studies/{{studyId}}/studyUrl

### download every session from a study
GET http://localhost:8080/api/studies/{{studyId}}/sessions/download


### make a question for a study
POST http://localhost:8080/api/studies/{{studyId}}/questions
Content-Type: application/json
Authorization: {{token}}

{
  "questionText": "What poem is happiest?",
  "questionType": "multiple-choice",
  "atifact": [],
  "options": [
    { "text": "The poem about summer" },
    { "text": "The poem about rain" }
  ]
}

### update question
PATCH http://localhost:8080/api/studies/{{studyId}}/questions/{{questionId}}
Content-Type: application/json
Authorization: {{token}}

{
  "questionText": "How did the poem make you feel?",
  "questionType": "text-box"
}

### delete question
DELETE http://localhost:8080/api/studies/{{studyId}}/questions/{{questionId}}
Authorization: {{token}}
